<div class="category-drop">
    <div class="custom-select">
        <select name="category">
            <option value="0">All categories</option>
            <option value="0">All categories</option>
            <option value="1">Anime</option>
                <option value="1_1">&nbsp;&nbsp;⮞&nbsp;&nbsp;Standalone Anime Movie</option>
                <option value="1_2">&nbsp;&nbsp;⮞&nbsp;&nbsp;OVA</option>
                <option value="1_3">&nbsp;&nbsp;⮞&nbsp;&nbsp;ONA</option>
                <option value="1_4">&nbsp;&nbsp;⮞&nbsp;&nbsp;Anime Series</option>
                <option value="1_5">&nbsp;&nbsp;⮞&nbsp;&nbsp;Anime Short</option>
                <option value="1_6">&nbsp;&nbsp;⮞&nbsp;&nbsp;AMV</option>
            <option value="2">Movies</option>
                <option value="2_7">&nbsp;&nbsp;⮞&nbsp;&nbsp;Standalone Movie</option>
                <option value="2_8">&nbsp;&nbsp;⮞&nbsp;&nbsp;Movie Series</option>
                <option value="2_9">&nbsp;&nbsp;⮞&nbsp;&nbsp;Short Film</option>
                <option value="2_10">&nbsp;&nbsp;⮞&nbsp;&nbsp;Teaser/Trailer</option>
                <option value="2_11">&nbsp;&nbsp;⮞&nbsp;&nbsp;Documentary</option>
            <option value="3">TV</option>
                <option value="3_12">&nbsp;&nbsp;⮞&nbsp;&nbsp;Show</option>
                <option value="3_13">&nbsp;&nbsp;⮞&nbsp;&nbsp;Episode</option>
                <option value="3_14">&nbsp;&nbsp;⮞&nbsp;&nbsp;Documentary Series</option>
                <option value="3_15">&nbsp;&nbsp;⮞&nbsp;&nbsp;Commercial Break</option>
            <option value="4">Games</option>
                <option value="4_16">&nbsp;&nbsp;⮞&nbsp;&nbsp;Videogame</option>
                <option value="4_17">&nbsp;&nbsp;⮞&nbsp;&nbsp;Visual Novel</option>
                <option value="4_18">&nbsp;&nbsp;⮞&nbsp;&nbsp;Point & Click</option>
                <option value="4_19">&nbsp;&nbsp;⮞&nbsp;&nbsp;Flash & Web</option>
                <option value="4_20">&nbsp;&nbsp;⮞&nbsp;&nbsp;ROM</option>
            <option value="5">Software</option>
                <option value="5_21">&nbsp;&nbsp;⮞&nbsp;&nbsp;Creative</option>
                <option value="5_22">&nbsp;&nbsp;⮞&nbsp;&nbsp;Office</option>
                <option value="5_23">&nbsp;&nbsp;⮞&nbsp;&nbsp;Utility</option>
                <option value="5_24">&nbsp;&nbsp;⮞&nbsp;&nbsp;Communications</option>
                <option value="5_25">&nbsp;&nbsp;⮞&nbsp;&nbsp;OS</option>
            <option value="6">NSFW</option>
                <option value="6_26">&nbsp;&nbsp;⮞&nbsp;&nbsp;Live Action</option>
                <option value="6_27">&nbsp;&nbsp;⮞&nbsp;&nbsp;Animated</option>
                <option value="6_28">&nbsp;&nbsp;⮞&nbsp;&nbsp;Pictures</option>
            <option value="7">Music</option>
                <option value="7_29">&nbsp;&nbsp;⮞&nbsp;&nbsp;Discography</option>
                <option value="7_30">&nbsp;&nbsp;⮞&nbsp;&nbsp;Album</option>
                <option value="7_31">&nbsp;&nbsp;⮞&nbsp;&nbsp;Single</option>
                <option value="7_32">&nbsp;&nbsp;⮞&nbsp;&nbsp;Live</option>
                <option value="7_33">&nbsp;&nbsp;⮞&nbsp;&nbsp;EP</option>
                <option value="7_34">&nbsp;&nbsp;⮞&nbsp;&nbsp;Music Video</option>
        </select>
    </div>
</div>